// ユーザー一覧の列定義
export const userColumns = [
  {
    label: "",
    dataKey: "_edit",
    width: 40,
    align: "center",
    headerAlign: "center",
  },
  {
    label: "ID",
    dataKey: "user_id",
    width: 80,
    align: "center",
    headerAlign: "center",
  },
  {
    label: "ログインID",
    dataKey: "login_id",
    width: 120,
    align: "left",
    headerAlign: "center",
    threePoint: true,
  },
  {
    label: "姓",
    dataKey: "last_name",
    width: 100,
    align: "left",
    headerAlign: "center",
    threePoint: true,
  },
  {
    label: "ユーザー名",
    dataKey: "user_name",
    width: 120,
    align: "left",
    headerAlign: "center",
    threePoint: true,
  },
  {
    label: "メール1",
    dataKey: "mail1",
    width: 200,
    align: "left",
    headerAlign: "center",
    threePoint: true,
  },
  {
    label: "性別",
    dataKey: "sex",
    width: 60,
    align: "center",
    headerAlign: "center",
  },
  {
    label: "権限",
    dataKey: "auth",
    width: 80,
    align: "center",
    headerAlign: "center",
  },
  {
    label: "ステータス",
    dataKey: "status",
    width: 80,
    align: "center",
    headerAlign: "center",
  },
  {
    label: "更新者",
    dataKey: "update_user",
    width: 100,
    align: "center",
    headerAlign: "center",
  },
  {
    label: "更新日時",
    dataKey: "updated_at",
    width: 240,
    align: "center",
    headerAlign: "center",
  },
];
