export const schema = {
    "auto_make_items": {
        "auto_make_items_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "project_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "プロジェクトID"
        },
        "title": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "タイトル"
        },
        "dir_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ディレクトリ名"
        },
        "url": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 128,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "URL"
        },
        "table_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 128,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "対象テーブル名"
        },
        "contents": {
            "type": "json",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "パラメータ"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "auto_make_test": {
        "id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "int_col": {
            "type": "int",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "int型"
        },
        "smallint_col": {
            "type": "smallint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "small int型"
        },
        "tinyint_col": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "tiny int型"
        },
        "mediumint_col": {
            "type": "mediumint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "medium int型"
        },
        "decimal_col": {
            "type": "decimal",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "decimal型"
        },
        "numeric_col": {
            "type": "decimal",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "numeric型"
        },
        "float_col": {
            "type": "float",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "float型"
        },
        "double_col": {
            "type": "double",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "double型"
        },
        "date_col": {
            "type": "date",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "date型"
        },
        "datetime_col": {
            "type": "datetime",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "datetime型"
        },
        "timestamp_col": {
            "type": "timestamp",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "timestamp型"
        },
        "time_col": {
            "type": "time",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "time型"
        },
        "year_col": {
            "type": "year",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "year型"
        },
        "char_col": {
            "type": "char",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 12,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "char型"
        },
        "varchar_col": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 255,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "varchar型"
        },
        "binary_col": {
            "type": "binary",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 3,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "binary型"
        },
        "varbinary_col": {
            "type": "varbinary",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 3,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "varbinary型"
        },
        "blob_col": {
            "type": "blob",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "blob型"
        },
        "text_col": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "text型"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "categories": {
        "category_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "カテゴリID"
        },
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "種別"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名称"
        },
        "comments": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "コメント"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "commons": {
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": true,
            "extra": "",
            "comment": "区分"
        },
        "id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": true,
            "extra": "",
            "comment": "ID"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名称"
        },
        "comments": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "コメント"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "status": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ステータス 1:削除済"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "component_explans": {
        "id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "プロパティ名称"
        },
        "explan": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "説明"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "compornent_explans": {
        "id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "コンポーネント名称"
        },
        "explan": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "説明"
        },
        "status": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ステータス 1:削除済"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "registuser": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "updateuser": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "dbms": {
        "dbms_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "dbms_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "DBMS名"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "status": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "状態"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "industries": {
        "industry_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "業界ID"
        },
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "1",
            "is_primary_key": false,
            "extra": "",
            "comment": "0:大区分"
        },
        "section_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "区分ID"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名称"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "prefectures": {
        "prefectury_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "都道府県ID"
        },
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "1",
            "is_primary_key": false,
            "extra": "",
            "comment": "区分 0:地方,1:都道府県"
        },
        "area_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "地方ID"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名称"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "projects": {
        "project_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "project_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名称"
        },
        "dbms_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "DBMS"
        },
        "db_server": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "サーバー名"
        },
        "db_port": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ポート番号"
        },
        "db_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "DB名"
        },
        "db_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "DBユーザー名"
        },
        "db_pass": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "DBパスワード"
        },
        "db_encoding": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "DB文字コード"
        },
        "template_id": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "テンプレートID"
        },
        "comments": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "コメント"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "status": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ステータス 1:削除済"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "settings": {
        "setting_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": ""
        },
        "contexts": {
            "type": "json",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": ""
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "src_templates": {
        "template_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "種別"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "テンプレート名"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "status": {
        "status_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "type": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "区分"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "ステータス名称"
        },
        "background_color": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 12,
            "default": "white",
            "is_primary_key": false,
            "extra": "",
            "comment": "背景カラーコード"
        },
        "color": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 12,
            "default": "black",
            "is_primary_key": false,
            "extra": "",
            "comment": "文字カラーコード"
        },
        "comments": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "コメント"
        },
        "sort": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "-1",
            "is_primary_key": false,
            "extra": "",
            "comment": "ソート順"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "unit_test": {
        "id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ID"
        },
        "name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名称"
        },
        "comments": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "コメント"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "論理削除フラグ"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "registuser": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "updateuser": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    },
    "users": {
        "user_id": {
            "type": "bigint",
            "is_null": false,
            "is_auto_increment": 1,
            "is_type_num": true,
            "max_length": null,
            "default": null,
            "is_primary_key": true,
            "extra": "auto_increment",
            "comment": "ユーザーID"
        },
        "login_id": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "ログインID"
        },
        "password": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "パスワード"
        },
        "password_key": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 12,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "パスワード暗号化キー"
        },
        "last_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名前(姓)"
        },
        "user_name": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名前(名)"
        },
        "katakana_last_name": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名前かたかな(姓)"
        },
        "katakana_name": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "名前かたかな(名)"
        },
        "mail1": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "メールアドレス１"
        },
        "is_send_mail1": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "1",
            "is_primary_key": false,
            "extra": "",
            "comment": "メールアドレス１送信フラグ"
        },
        "mail2": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "メールアドレス２"
        },
        "is_send_mail2": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "メールアドレス２送信フラグ"
        },
        "mail3": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "メールアドレス３"
        },
        "is_send_mail3": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "メールアドレス３送信フラグ"
        },
        "incoming_mail_format": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "受信メール形式"
        },
        "sex": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "性別 0:男性,1:女性"
        },
        "post_first_no": {
            "type": "smallint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "郵便番号(上3桁)"
        },
        "post_last_no": {
            "type": "smallint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "郵便番号(下4桁)"
        },
        "province_id": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "都道府県ID"
        },
        "address1": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 128,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "住所１"
        },
        "address2": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 128,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "住所２"
        },
        "address3": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 128,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "住所３"
        },
        "nearest_station": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "最寄駅"
        },
        "birthplace": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "出身地"
        },
        "date_of_birth": {
            "type": "datetime",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "1900-01-01 00:00:00",
            "is_primary_key": false,
            "extra": "",
            "comment": "生年月日"
        },
        "nationality": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "国籍"
        },
        "official_position": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "役職"
        },
        "department": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "部門"
        },
        "organization": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 64,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "組織"
        },
        "is_smoking": {
            "type": "tinyint",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "喫煙フラグ true:禁煙 false:喫煙"
        },
        "blood_type": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "血液型 A:1, O:2, B:3, AB:4"
        },
        "is_spouse": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "配偶者有無"
        },
        "comments": {
            "type": "text",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 65535,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "コメント"
        },
        "auth": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ユーザー権限"
        },
        "login_state": {
            "type": "smallint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "ログイン状態"
        },
        "first_login_date": {
            "type": "datetime",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "初回ログイン日時"
        },
        "is_deleted": {
            "type": "tinyint",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "物理削除"
        },
        "dbcount": {
            "type": "int",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": true,
            "max_length": null,
            "default": "0",
            "is_primary_key": false,
            "extra": "",
            "comment": "更新回数"
        },
        "created_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED",
            "comment": "登録日時"
        },
        "regist_user": {
            "type": "varchar",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": "",
            "is_primary_key": false,
            "extra": "",
            "comment": "登録者"
        },
        "updated_at": {
            "type": "timestamp",
            "is_null": false,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": null,
            "default": "CURRENT_TIMESTAMP",
            "is_primary_key": false,
            "extra": "DEFAULT_GENERATED on update CURRENT_TIMESTAMP",
            "comment": "更新日時"
        },
        "update_user": {
            "type": "varchar",
            "is_null": true,
            "is_auto_increment": 0,
            "is_type_num": false,
            "max_length": 32,
            "default": null,
            "is_primary_key": false,
            "extra": "",
            "comment": "更新者"
        }
    }
};